version: '3.8'

services:
  testops-export:
    build: .
    container_name: testops-export
    restart: unless-stopped
    ports:
      - "9090:9090"
    environment:
      - TESTOPS_TOKEN=${TESTOPS_TOKEN}
      - TESTOPS_BASE_URL=${TESTOPS_BASE_URL:-https://allure-testops.wb.ru}
      - EXPORT_PATH=/app/exports
      - WEB_PORT=9090
      - CRON_SCHEDULE=${CRON_SCHEDULE:-0 7 * * *}
    volumes:
      - ./exports:/app/exports
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 