version: '3.8'

services:
  testops-export:
    image: testops-export:latest
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    environment:
      - TESTOPS_TOKEN=${TESTOPS_TOKEN}
      - TESTOPS_BASE_URL=${TESTOPS_BASE_URL:-https://allure-testops.wb.ru}
      - EXPORT_PATH=/app/exports
      - WEB_PORT=9090
      - CRON_SCHEDULE=${CRON_SCHEDULE:-0 7 * * *}
    ports:
      - "9090:9090"
    volumes:
      - ./exports:/app/exports
    networks:
      - testops-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  testops-network:
    driver: overlay
    attachable: true 