version: '3.8'

services:
  testops-export:
    image: testops-export:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TESTOPS_TOKEN=${TESTOPS_TOKEN}
      - TESTOPS_BASE_URL=${TESTOPS_BASE_URL}
      - EXPORT_PATH=/app/exports
      - WEB_PORT=9090
      - CRON_SCHEDULE=${CRON_SCHEDULE:-0 7 * * *}
    ports:
      - "9090:9090"
    volumes:
      - ./exports:/app/exports
    networks:
      - testops-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  testops-network:
    driver: bridge 