apiVersion: apps/v1
kind: Deployment
metadata:
  name: testops-export-case
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testops-export-case
  template:
    metadata:
      labels:
        app: testops-export-case
    spec:
      serviceAccountName: leader-election-sa
      volumes:
        - name: exports-volume
          persistentVolumeClaim:
            claimName: exports-pvc
        - name: projects-config
          configMap:
            name: projects-config
      containers:
      - name: testops-export-case
        image: testops-export:1.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
        envFrom:
        - configMapRef:
            name: testops-export-case-config
        volumeMounts:
          - name: exports-volume
            mountPath: /app/exports
          - name: projects-config
            mountPath: /app/projects.json
            subPath: projects.json
