apiVersion: v1
kind: PersistentVolume
metadata:
  name: exports-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/Pavlov.Stanislav26/Downloads/dev/utils/testops-export-case/exports"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exports-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
