apiVersion: v1
kind: Service
metadata:
  name: testops-export-case-service
spec:
  type: NodePort
  selector:
    app: testops-export-case
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9090
      nodePort: 30080

